kind: pipeline
name: default

clone:
  depth: 50
steps:
  - name: install
    image: composer
    commands:
      - ls -al
      - sudo apt-get -y update
      - sudo apt-get -y purge docker.io
      - sudo apt-get -y install docker.io
      - sudo rm /usr/local/bin/docker-compose
      - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      - ls -al
      - cp .env.example .env
      - cp docker-compose.yml.example docker-compose.yml
      - docker-compose up -d --build
      - docker-compose ps
      - docker ps
      - docker-compose exec shop-db bash
      - mysql -u root -p
      - root
#      - vendor/bin/phpunit
#  - name: test
#    image: php
#    commands:
#      - vendor/bin/phpunit
#    when:
#      branch:
#        - master
#services:
#  - name: database
#    image: mysql
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      MYSQL_DATABASE: nuxt_shop
#    command:
#      - ls -al
#      - mysql --default-character-set=utf8 nuxt_shop < nuxt_shop.sql
#  build:
#    image:php:7.4-fpm-alpine3.10
#    commands:
#      - composer install
#      - vendor/bin/phpunit
