kind: pipeline
type: docker
name: default
#clone:
#  depth: 50
steps:
  - name: install
    image: composer
    commands:
      - composer install
      - cp .env.example .env
      - php artisan migrate
      - ls -al
      - mysql --default-character-set=utf8 nuxt_shop < nuxt_shop.sql
  - name: test
    image: php
    commands:
      - vendor/bin/phpunit
    when:
      branch:
        - master
services:
  - name: database
    image: mysql
    base: /usr bin
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: nuxt_shop
    command:
      - show databases;
#      - mysql --default-character-set=utf8 nuxt_shop < nuxt_shop.sql
#  build:
#    image:php:7.4-fpm-alpine3.10
#    commands:
#      - composer install
#      - vendor/bin/phpunit
