kind: pipeline
type: docker
name: default
clone:
  depth: 50
steps:
  - name: build
    image: ./docker/
    commands:
      - cp .env.example .env
      - cp docker-compose.yml.example docker-compose.yml
      - docker-compose up -d --build
      - docker-compose exec shop-db bash
      - mysql -u root -p
      - root
      - SHOW DATABASES;
      - CREATE DATABASE nuxt_shop;
#      - composer install
  - name: test
    image: php
    commands:
      - vendor/bin/phpunit
    when:
      branch:
        - master
#pipeline:
#  build:
#    image:php:7.4-fpm-alpine3.10
#    commands:
#      - composer install
#      - vendor/bin/phpunit
