# 以下為docker環境設置
# docker + 外部mysql (mysql放docker內暫時無法)
sudo: required

services:
  - docker
  - mysql
env:
  DOCKER_COMPOSE_VERSION: 1.27.0-rc1
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
#  DB_DATABASE: nuxt_shop
#  DB_USERNAME: root
#  DB_PASSWORD: root
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y purge docker.io
  - sudo apt-get -y install docker.io
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo mysql -e "CREATE DATABASE nuxt_shop;"
#  - sudo mysql -e 'SHOW DATABASES;'
#  - mysql -e "SET PASSWORD = PASSWORD('${DB_PASSWORD}');"
#  - ls -lah
  - sudo mysql --default-character-set=utf8 nuxt_shop < nuxt_shop.sql
#  - sudo mysql -e 'SHOW DATABASES;'
#  - mysql -e "mysql -u root -proot  nuxt_shop < nuxt_shop.sql;"
before_script:
#  - ls -lah
  - cp .env.example .env
  - cp docker-compose.yml.example docker-compose.yml
  - docker-compose up -d --build
#  - sudo cp nuxt_shop.sql docker/mysql/nuxt_shop.sql
#  - service docker restart
  - docker-compose ps
  - docker container ps
script:
#  docker exec -it testlumen_shop-web_1 bash -c "
#  cd /var/www && \
#  composer install&& \
#  vendor/bin/phpunit "
#  - docker exec -it testlumen_shop-web_1 bash -c " /var/www/vendor/bin/phpunit "
  - docker-compose exec shop-web bash 
#  - cd /var/www && composer install && vendor/bin/phpunit

after_script:
  - docker-compose down

#    佈署相關資訊
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local-dir: public
#  repo: ms314006/ms314006.github.io
#  target_branch: master

